### ISSUE TITLE
Tablature and Lines become unalligned

### ISSUE THREAD

**Issue by dcollis92** [Rock-n-Roll-Coders/RIFFIN-FRONTEND#1]
While creating my lesson plan for my guitar student, I noticed this issue happening while attempting to duplicate the 3rd line. I saved it, refreshed, exited, and went back. Still the same. 

<img width="789" alt="Screen Shot 2023-02-06 at 5 26 11 PM" src="https://user-images.githubusercontent.com/95148980/217110554-782059aa-45c2-47f2-946c-588f167e01da.png">

**Comment by RyanSUP** [comment]
Good catch dude! I'll add it to jira.
